# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JagaAdminMobileApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JagaAdminMobileApp
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  target 'JagaAdminMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end